services:
  # Backend API service
  - type: web
    name: pigeonrtc-api
    env: docker
    repo: https://github.com/Alvinmutuma/pigeonsRTC
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        fromService:
          type: web
          name: pigeonrtc-web
          property: host
      - key: JWT_SECRET
        sync: false # This will be set manually for security
      - key: MONGODB_URI
        sync: false # Will connect to MongoDB Atlas

  # Frontend web client
  - type: web
    name: pigeonrtc-web
    env: docker
    repo: https://github.com/Alvinmutuma/pigeonsRTC
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: pigeonrtc-api
          property: host
  # Render-managed Redis instance
  - type: redis
    name: pigeonrtc-cache
    plan: free
    ipAllowList: [] # allow all IPs
    # maxmemoryPolicy: allkeys-lru # Example: You can set Redis-specific options


